// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9CLrYFYh-i8suRi5fIXzGnVlmLCijoJA',
    appId: '1:781422240890:web:9d10882d54fb4925f1c7c3',
    messagingSenderId: '781422240890',
    projectId: 'duitqu-c3346',
    authDomain: 'duitqu-c3346.firebaseapp.com',
    storageBucket: 'duitqu-c3346.firebasestorage.app',
    measurementId: 'G-BD2WLRMBDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn7hLI_YLCbAD30Y_a9mWc0TweuB8Ed_M',
    appId: '1:781422240890:android:291a0b7a56851e27f1c7c3',
    messagingSenderId: '781422240890',
    projectId: 'duitqu-c3346',
    storageBucket: 'duitqu-c3346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFIGax9GFF77qPxfBU56DXFah7CwT1J8Y',
    appId: '1:781422240890:ios:8c5af1080fab4c59f1c7c3',
    messagingSenderId: '781422240890',
    projectId: 'duitqu-c3346',
    storageBucket: 'duitqu-c3346.firebasestorage.app',
    iosBundleId: 'com.example.manajemenKeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFIGax9GFF77qPxfBU56DXFah7CwT1J8Y',
    appId: '1:781422240890:ios:8c5af1080fab4c59f1c7c3',
    messagingSenderId: '781422240890',
    projectId: 'duitqu-c3346',
    storageBucket: 'duitqu-c3346.firebasestorage.app',
    iosBundleId: 'com.example.manajemenKeuangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9CLrYFYh-i8suRi5fIXzGnVlmLCijoJA',
    appId: '1:781422240890:web:89b27e162a678265f1c7c3',
    messagingSenderId: '781422240890',
    projectId: 'duitqu-c3346',
    authDomain: 'duitqu-c3346.firebaseapp.com',
    storageBucket: 'duitqu-c3346.firebasestorage.app',
    measurementId: 'G-B4V1ET7PLW',
  );

}